import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useAppState } from "../components/app-state";

const inter = Inter({ subsets: ["latin"] });

export default function Root(): JSX.Element {
  const { state, dispatch } = useAppState();

  // eslint-disable-next-line no-console -- just testing
  console.log("state", state);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <Link href="/home">Home</Link>
          <button
            onClick={() => {
              dispatch({ type: "SET_AUTHENTICATED" });
            }}
            type="button"
          >
            Log in
          </button>
        </div>
      </main>
    </>
  );
}
